### ISSUE TITLE
Support inno installers

### ISSUE THREAD

**Issue by rfuzzo** [WolvenKit/WolvenKit.Installer#1]
- [ ] Switch zip extraction for inno installers 
- [ ] use uninstallers

- [ ] Check update functionality
- [ ] Check start menu shortcut creation

**Comment by avail** [comment]
Have you given Squirrel a thought?

**Comment by rfuzzo** [comment]
> Have you given Squirrel a thought?

Hi avail, hows it going? :) yes I have, but it seems unmaintained at the moment, right?

also I recently made the WolvenKit ci create inno installers and they have a /VERYSILENT switch out of the box. Should be simple to implement…


Ill checkout squirrel again though, thanks for the reminder !
