### ISSUE TITLE
Unable to install - Certificate issue

### ISSUE THREAD

**Issue by Frost212** [WolvenKit/WolvenKit.Installer#9]
So after reinstalling windows, i am unable to install this due to this error:

 `Either you need a new certificate installed for this app package, or you need a new app package with trusted certificates. Your system administrator or the app developer can help. A certificate chain processed, but terminated in a root certificate which isn't trusted (0x800B0109)`

I did download the certificate file you included in the most recent release and installed it before hand (tried installing the certificate both ways) and even restarted my PC between install attempts, still results in the same error

**Comment by danielmaciejpytel** [comment]
I found a fix. 
You need to install the cerfificate to Trusted Root Certification Authorities
![certificate-step2](https://github.com/user-attachments/assets/fbaa2da5-ba00-4a9b-a339-c0f76207c622)

**Comment by Frost212** [comment]
Edit: Nevermind. Installing it as local machine into trusted people (per https://learn.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues ) managed to get it working.
